config/routes.rb
Rails.application.routes.draw do

  root to: "posts#index"
  get "posts/new", to: "posts#new", as: "posts_new"
  post "posts", to: "posts#create", as: "create_post"

  get "posts/:id/edit", to: "posts#edit", as: "posts_edit"
  patch "posts/:id/update", to: "posts#update", as: "post_update"
  get "posts/:id", to: "posts#show", as: "posts_display"
  get "posts/:id/delete", to: "posts#delete", as: "posts_delete"

  get "logins/new", to: "logins#new", as: "logins"
  get "logins", to: "logins#show", as: "show_login"
  post "logins", to: "logins#create", as: "create_login"
  get "logins/:id/delete", to: "logins#delete", as: "logouts"

  get "new_users/new", to: "new_users#new", as: "users_new"
  post "new_users", to: "new_users#create", as: "register_users"

  get "posts/:id", to: "comments#new", as: "new_comments"
  post "posts/:id", to: "comments#create", as: "comment_on_post"
  get "posts/:id/edit", to: "comments#edit", as: "comments_edit"
  get "comments/:id/delete", to: "comments#delete", as: "delete_comment"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  max_paginates_per 15
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true, uniqueness: true,
    format: {
      with: /.+\@.+\..+/,
      message: "must have an @ symbol and period"
    }

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    user_id = session[:user_id]
    if user_id
      User.find_by(id: user_id)
    end
  end

  def authenticate!
    unless current_user
      flash[:notice] = "You must be logged in to do that."
      redirect_to :root
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params["id"])
    new_comment = @post.comments.create(body: params["body"],
                                        post_id: @post.id,
                                        user_id: current_user.id)
    redirect_to posts_display_path(params["id"])
  end

  # def edit
  #   @comment = Comment.find(params["id"])
  #   render :edit, locals: {comment: @comment}
  # end
  #
  # def update
  #   @comment = Comment.find(params["id"])
  #   @comment.update(body: params["body"])
  #   redirect_to posts_display_path(params["post_id"])
  # end
  #
  def delete
    @comment = Comment.find(params["id"])
    post_id = @comment.post_id
    @comment.destroy
    redirect_to posts_display_path(post_id)
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    render "logins/login.html.erb"
  end

  def create
    @user = User.find_by(email: params["email"])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to :root
    else
      flash[:notice] = "Wrong email and/or password."
      render "logins/login.html.erb"
    end
  end

  def show
    @user = @user.find(params["id"])
  end

  def delete
    session[:user_id] = nil
    redirect_to :root
  end
end

app/controllers/new_users_controller.rb
class NewUsersController < ApplicationController
  def new
    render "new_user/new_user_login.html.erb"
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.permit(:username, :email, :password, :confirmation, :full_name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @posts = Post.page(params[:page]).per(10)
    render :index, locals: { posts: @posts }
  end

  def new
    render :new
  end

  def create
    new_post = current_user.posts.create(title: params["title"],
                           content: params["content"])
    redirect_to :root
  end

  def edit
    @post = Post.find(params["id"])
    render :edit, locals: {post: @post}
  end

  def update
    right_now = DateTime.now
    @post = Post.find(params["id"])
    @post.update(title: params["title"],
                content: params["content"])
    @post.updated_at = right_now
    redirect_to :root
  end

  def show
    @post = Post.find(params["id"])
    render :show
  end

  def delete
    @post = Post.find(params["id"])
    comments = Comment.where(post_id: @post.id)
    comments.each do |comment|
      comment.destroy
    end
    @post.destroy
    redirect_to :root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
  <nav>
    <div class="left nav-wrapper">
      <div class="side_padding_div">
        Hello <%= User.find_by(id: session[:user_id]).username %>
      </div>
    </div>
    </div>
    <div class="right nav-wrapper">
      <div class="side_padding_div">
        <%= link_to("Logout", logouts_path(id: session[:user_id])) %>
      </div>
    </div>
  </nav>
  <% else %>
  <nav>
    <div class="right nav-wrapper">
      <div class="side_padding_div">
        <%= link_to("Sign In Here", logins_path) %>
      </div>
    </div>
  </nav>
  <% end %>

<%= yield %>

</body>
</html>

app/views/logins/login.html.erb
<div class="side_padding_div">
  <%= link_to("New users sign in here", users_new_path) %>

  <h3>Login</h3>


  <%= form_tag(create_login_path) do %>
       <div class="login-field">
           <%= label_tag("Email:") %>
           <%= text_field_tag("email") %>
      </div>

       <div class="login-field">
           <%= label_tag("Password:") %>
           <%= password_field_tag("password") %>
      </div>
       <button class="btn waves-effect waves-light" type="submit" name="action">
         submit
       </button>
  <% end %>


  <%= link_to("Return to Homepage", root_path) %>
</div>

app/views/new_user/new_user_login.html.erb
<div class="side_padding_div">
  <h2>New User Login</h2>

  <%= form_tag(register_users_path) do %>
    <div class="login-field">
      <%= label_tag("Username:") %>
      <%= text_field_tag("username") %>
    </div>

    <div class="login-field">
      <%= label_tag("Email:") %>
      <%= text_field_tag("email") %>
    </div>

    <div class="login-field">
      <%= label_tag("Password:") %>
      <%= password_field_tag("password") %>
    </div>

    <div class="login-field">
      <%= label_tag("Confirm Password") %> <br/>
      <%= password_field_tag("password_confirmation") %>
    </div>

    <button class="btn waves-effect waves-light" type="submit" name="action">
      submit
    </button>
  <% end %>
  <p>
  <%= link_to("Return to Login Page", logins_path) %></br>
  <%= link_to("Return to Homepage", root_path) %>
</div>

app/views/posts/edit.html.erb
<div class="side_padding_div">
  <h3>Update Post</h3>
  <%=  form_tag(post_update_path(@post), method: :patch) do %>
      <div class="post-field">
          <%= label_tag("Title: ") %>
          <%= text_field_tag("title", @post.title) %>
      </div>

      <div class="post-field">
          <%= label_tag("Content: ") %>
          <%= text_area_tag("content", @post.content) %>
      </div>

      <button class="btn waves-effect waves-light" type="submit" name="action">
        Update Post
      </button>
  <% end %>
  <%= link_to("Return to Homepage", root_path) %>
</div>

app/views/posts/index.html.erb
<div class="side_padding_div">
  <div class="top_left_link">
    <% if current_user %>
      <%= link_to("Add a New Post!", posts_new_path) %>
    <% end %>
  </div>

  <div class="title_div">
    BLOG POSTINGS
  </div>

    <% @posts.each do |post| %>
          <div class="card grey lighten-4">
            <span class="card-title">
              <b>Title:</b> <%= post.title %>
              <div class="poster">
                <% poster= User.find_by(id: post.user_id) %>
                posted by <b><u><%= poster.username %></u></b>
                <%= time_ago_in_words(post.updated_at) %> ago
              </div>
            </span>
              <div class="content_title">
                <b>Content:</b>
                <i><%= post.content %></i>
              </div>
              <ul class="options">
                <li><%=link_to("display post (lets you view and make comments)",
              posts_display_path(post.id)) %></li>
                <% if session[:user_id] == post.user_id %>
                <li><%=link_to("edit post ", posts_edit_path(post.id)) %></li>
                <li><%=link_to("delete post ", posts_delete_path(post.id)) %></li>
                <% end %>
            </ul>
          </div>
    <% end %>
  </ul>
</div>
<% scope = Post.all.page(params[:page]).per(10) %>
  <%= paginate(scope) %>

app/views/posts/new.html.erb
<!-- <form class="new-post" action="/posts" method="post"> -->
<!-- <div class="post-field"> -->
<!-- <label>Title: </label> <br/> -->
<!-- <input type="text" name="title"> -->
<!-- </div>  -->

<!-- <div class="post-field"> -->
<!-- <label>Content: </label> <br/> -->
<!-- <input type="textarea" name="content"> -->
<!-- </div> -->

<!-- <button type="submit">Create Post!</button> -->
<!-- </form> -->

<div class="side_padding_div">
  <%=  form_tag(create_post_path) do %>
      <div class="post-field">
          <%= label_tag("Title: ") %>
          <%= text_field_tag("title") %>
      </div>

      <div class="post-field">
          <%= label_tag("Content: ") %>
          <%= text_area_tag("content") %>
      </div>

      <button class="btn waves-effect waves-light" type="submit" name="action">
        Create Post
      </button>
  <% end %>

  <%= link_to("Return to Homepage", root_path) %>
</div>

app/views/posts/show.html.erb
<div class="side_padding_div">
  <div class="top_left_link">
    <%= link_to("Return to Homepage", root_path) %>
  </div>

  <div class="poster2">
    <% poster= User.find_by(id: @post.user_id) %>
    posted by <%= poster.username %>
    <%= time_ago_in_words(@post.updated_at) %> ago
  </div>

  <div class="card-panel blue">
    <span class="white-text">
      <b><u>title:</b></u>  <%=@post.title %></br>
      <b><u>content:</b></u>  <%=@post.content %>
    </span>
  </div>

  <div class="comments_intro">
    Comments:
  </div>

  <div class="comments">
    <% @post.comments.each do |comment| %>
      <% if current_user %>
        <% u_id = current_user.id %>
      <% else %>
        <% u_id = 0 %>
      <% end %>
        <div class="card">
          <span class="card-title">
            <%= comment.body %>
          </span>
            <p><i>comment posted by
              <% poster= User.find_by(id: comment.user_id) %>
            <b><u><%= poster.username %></u></b>
            <%= time_ago_in_words(comment.updated_at) %> ago </i>
            <% if comment.user_id == u_id %>
            <div class="card-action">
              <%= link_to("Delete Comment", delete_comment_path(comment.id)) %>
            </div>
            <% end %>
        </div>
    <% end %>
  </div>
  </br>
  <%=  form_tag(comment_on_post_path(@post.id)) do %>
      <div class="post-field">
          <b><%= label_tag("Write Comment Here: ") %></b> <br/>
          <%= text_area_tag("body") %>
      </div>

      <button class="btn waves-effect waves-light" type="submit" name="action">
        Post Comment
      </button>
  <% end %>
</div>